n_train = [3, 10, 30, 100, 300, -1]
n_test = [-1]

newt_root = "/$NFS/workspace/$USER/datasets/newt"

# SigLIP
[[models]]
method = "cvml"
org = "open-clip"
ckpt = "ViT-B-16-SigLIP/webli"

[[models]]
method = "cvml"
org = "open-clip"
ckpt = "ViT-B-16-SigLIP-256/webli"

[[models]]
method = "cvml"
org = "open-clip"
ckpt = "ViT-B-16-SigLIP-384/webli"

[[models]]
method = "cvml"
org = "open-clip"
ckpt = "ViT-B-16-SigLIP-512/webli"

[[models]]
method = "cvml"
org = "open-clip"
ckpt = "ViT-L-16-SigLIP-256/webli"

[[models]]
method = "cvml"
org = "open-clip"
ckpt = "ViT-L-16-SigLIP-384/webli"

[[models]]
method = "cvml"
org = "open-clip"
ckpt = "ViT-SO400M-14-SigLIP/webli"

[[models]]
method = "cvml"
org = "open-clip"
ckpt = "ViT-SO400M-14-SigLIP-384/webli"
