prompting = ["single"]
cot_enabled = false
parallel = 25

n_train = [0, 1, 3, 10, 30, 100]
n_test = 100

newt_root = "$NFS/$USER/datasets/newt"

# Smaller models

[[models]]
method = "mllm"
org = "openrouter"
ckpt = "qwen/qwen-2-vl-7b-instruct"

[[models]]
method = "mllm"
org = "openrouter"
ckpt = "google/gemini-flash-1.5-8b"

# Larger models

[[models]]
method = "mllm"
org = "openrouter"
ckpt = "google/gemini-2.0-flash-001"

[[models]]
method = "mllm"
org = "openrouter"
ckpt = "qwen/qwen2.5-vl-72b-instruct"
